sudo: required

language: cpp 

compiler:
  - clang
  - gcc

services:
  - docker
  
before_install:
  - docker build -t dit168 .
  - docker run --rm --net=host dit168

script:
  - docker ps -a

notifications:
   slack: dit168group13:yZbuGhcJe2rGqwREIHRspcYi
   on_success: change
   on_failure: always
