# Copyright (C) 2016 DIT168 - Group 13
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

version: '2'

services:

    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=111 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=111 --freq=50 --id=1"

    # Micro service for PS4 controller.
    proxy-miniature-ps4controller:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        devices:
        - "/dev/input/js0:/dev/input/js0"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-ps4controller --cid=224 --freq=10 --verbose=1"
 
    # Micro service for ultrassonic sensors.
    device-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.6
        network_mode: "host"
        privileged: true
        volumes:
          - /dev/i2c-1:/dev/i2c-1
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=112 --cid=111 --freq=5 --id=0"
    
    device-ultrasonic-srf08-rear:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.6
        network_mode: "host"
        privileged: true
        volumes:
          - /dev/i2c-1:/dev/i2c-1
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=113 --cid=111 --freq=5 --id=1"
    
    # Micro service for infrared sensors.
    device-adc-bbblue-left:
        image: chalmersrevere/opendlv-device-adc-bbblue-armhf:v0.0.6
        network_mode: "host"
        privileged: true
        volumes:
          - /dev/mem:/dev/mem
        command: "/usr/bin/opendlv-device-adc-bbblue --cid=111 --freq=5 --channel=2 --id=0"
    
    device-adc-bbblue-right:
        image: chalmersrevere/opendlv-device-adc-bbblue-armhf:v0.0.6
        network_mode: "host"
        privileged: true
        volumes:
          - /dev/mem:/dev/mem
        command: "/usr/bin/opendlv-device-adc-bbblue --cid=111 --freq=5 --channel=3 --id=1"
 
 # Our microservice. // NEEDS FIXING 
    example:
        image: example
	depends_on:
	- proxy-miniature-pwm-motor
        network_mode: "host"
        restart: always
        command: "/opt/example --cid=111 --freq=10"
