# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-09-09

version: '2'

services:
    # micro service for PS3 controller.
    proxy-miniature-ps3controller:
        image: ${IMAGE_ARM}
        network_mode: "host"
        restart: always
        devices:
        - "/dev/input/js0:/dev/input/js0"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-ps3controller --cid=${CID} --freq=10"

    #proxy-miniature-pwm-motor:
    #   image: ${IMAGE_ARM}
    #   network_mode: "host"
    #   restart: always
    #   privileged: true
    #   volumes:
    #   - /sys/:/sys/
    #   - /dev/:/dev/
    #   command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=${CID} --freq=50 --id=1"

